/**
 * Make this video's sound effects, rather than download them.
 *
 *   node ../pipeline/make-sfx.mjs            # → input/sfx/*.wav
 *   node ../pipeline/make-sfx.mjs --force    # rebuild files that already exist
 *
 * **Why synthesised and not from a library.** `STORE-ASSETS.md` says every
 * third-party asset in this repository needs a source and a commercial licence
 * written down in `CREDITS.md` before it ships, and the same rule is why there
 * is no music and no stock footage anywhere in these videos. A free-sound pack
 * whose licence nobody has read is the exact thing that rule exists to stop.
 * These are tones and filtered noise generated by ffmpeg from nothing, so the
 * licence question does not arise and `CREDITS.md` stays honest.
 *
 * **Nothing is ever heard twice in one video.** The first version of this had
 * three cut sounds and rotated them across nine beats, so each was heard three
 * times; that was still audibly a loop. A video needs at most nine cuts, twelve
 * moves of each kind, one opener and one riser, so this makes **one distinct
 * file for every event a video can contain** and `Sfx.tsx` hands out a fresh
 * index each time. No file is used twice in the same render.
 *
 * **They are a family, not a collection.** Randomly different sounds in one
 * video is as wrong as one sound nine times — it reads as a soundboard. The
 * cuts walk *down* a pentatonic series as the tutorial proceeds, the marks walk
 * *up*, and the moves open and close progressively brighter bands. Each is
 * plainly its own sound and plainly related to the one before it.
 *
 * Everything is under a second, none of it is musical enough to read as music,
 * and `Sfx.tsx` keeps the levels well under the voice.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

import { PROJECT } from './lib.mjs';

const DIR = resolve(PROJECT, 'input/sfx');
const force = process.argv.includes('--force');
mkdirSync(DIR, { recursive: true });

const SR = 48000;
const pad = (n) => String(n).padStart(2, '0');

/**
 * One file from one `aevalsrc` expression — ffmpeg's "compute every sample from
 * this formula" source, so a tick is a sine times a decaying exponential and
 * nothing has to be recorded. Mono in, stereo out: a sound this short with any
 * width in it reads as a glitch on one earbud.
 */
const tone = (name, expr, dur) => {
  const out = resolve(DIR, `${name}.wav`);
  if (existsSync(out) && !force) return false;
  execFileSync(
    'ffmpeg',
    ['-v', 'error', '-y',
     '-f', 'lavfi', '-i', `aevalsrc='${expr}':d=${dur}:s=${SR}`,
     '-af', 'aformat=channel_layouts=stereo,alimiter=limit=0.9',
     '-c:a', 'pcm_s16le', out],
    { stdio: 'inherit' }
  );
  return true;
};

/** Filtered noise, for the moves. A whoosh is a band of noise that opens and shuts. */
const noise = (name, dur, filters) => {
  const out = resolve(DIR, `${name}.wav`);
  if (existsSync(out) && !force) return false;
  execFileSync(
    'ffmpeg',
    ['-v', 'error', '-y',
     '-f', 'lavfi', '-i', `anoisesrc=c=pink:d=${dur}:r=${SR}:a=0.5`,
     '-af', [...filters, 'aformat=channel_layouts=stereo', 'alimiter=limit=0.9'].join(','),
     '-c:a', 'pcm_s16le', out],
    { stdio: 'inherit' }
  );
  return true;
};

console.log(`\n${DIR}`);
let made = 0;

// ── cuts, one per beat ─────────────────────────────────────────────────────
// Nine of them, walking down a pentatonic series, so the ninth beat sounds
// lower and more settled than the first without any of them being a tune. Low
// and short: felt more than heard, which is what keeps nine in a minute from
// becoming a woodpecker.
const CUT_HZ = [196, 175, 165, 147, 131, 123, 110, 98, 87];
CUT_HZ.forEach((f, i) => {
  const decay = 30 - i * 1.2;
  if (tone(`cut-${pad(i + 1)}`, `0.85*(sin(2*PI*${f}*t)+0.25*sin(2*PI*${f * 2}*t))*exp(-${decay}*t)`, 0.26)) made += 1;
});

// ── moves, one per lean-in and one per pull-back ───────────────────────────
// Twelve of each, which is more than any beat list here uses. Bands open
// progressively as the index rises so a later move is a shade brighter than an
// earlier one; noise rather than tone, because a pitched swell under a voice
// reads as music starting and this is not music.
for (let i = 0; i < 12; i += 1) {
  const hp = 260 + i * 34;
  const lp = 3000 + i * 260;
  const d = (0.34 + (i % 4) * 0.03).toFixed(2);
  if (noise(`in-${pad(i + 1)}`, d, [
    `highpass=f=${hp}`, `lowpass=f=${lp}`,
    `afade=t=in:d=${(d * 0.62).toFixed(2)}:curve=ipar`,
    `afade=t=out:st=${(d * 0.7).toFixed(2)}:d=${(d * 0.3).toFixed(2)}`,
    'volume=0.5',
  ])) made += 1;

  const od = (0.3 + (i % 3) * 0.03).toFixed(2);
  if (noise(`out-${pad(i + 1)}`, od, [
    `highpass=f=${200 + i * 18}`, `lowpass=f=${2200 + i * 160}`,
    'afade=t=in:d=0.04',
    `afade=t=out:st=0.08:d=${(od - 0.08).toFixed(2)}:curve=ipar`,
    'volume=0.42',
  ])) made += 1;
}

// ── marks, one per box landing ─────────────────────────────────────────────
// Walking up where the cuts walk down, so a beat's cut and its mark move apart
// rather than together. A fifth on top of each, which is what makes a short
// sine read as a mark rather than a beep.
const MARK_HZ = [622, 659, 698, 740, 784, 831, 880, 932, 988, 1047, 1109, 1175];
MARK_HZ.forEach((f, i) => {
  if (tone(`mark-${pad(i + 1)}`, `0.5*(sin(2*PI*${f}*t)+0.4*sin(2*PI*${Math.round(f * 1.5)}*t))*exp(-${25 + i * 0.4}*t)`, 0.24)) made += 1;
});

// ── openers, one per hook ──────────────────────────────────────────────────
// Seven, so the seven finished videos do not all begin on the same note. The
// first frame carries more weight than a cut, so these are longer and have a
// body under them.
const OPEN_HZ = [150, 138, 128, 116, 110, 98, 92];
OPEN_HZ.forEach((f, i) => {
  if (tone(`open-${pad(i + 1)}`, `0.9*(sin(2*PI*${f}*t)+0.3*sin(2*PI*${f * 2}*t))*exp(-${16 - i * 0.8}*t)`, 0.45)) made += 1;
});

// ── the close ──────────────────────────────────────────────────────────────
// One riser, used once, under the last beat. A sound that happens once is the
// only kind that can mean "this is the end".
if (noise('riser', 0.9, ['highpass=f=200', 'lowpass=f=6000', 'afade=t=in:d=0.8:curve=exp', 'afade=t=out:st=0.82:d=0.08', 'volume=0.45'])) made += 1;

console.log(`  ${made} file(s) written${made ? '' : ' — all already there, pass --force to rebuild'}`);
console.log('\nGenerated, not licensed — see the header. CREDITS.md stays empty.');
