#!/usr/bin/env bash
# Stage this video's media where Remotion can see it.
#
# Remotion serves `staticFile()` out of its own `public/`, which is out of git
# for the reason the root .gitignore gives: it is nothing but copies. The source
# of truth for each kind lives where it belongs — the fonts in `assets/fonts/`
# with the burn-in module, the app recordings and the export in this project's
# `input/app/` where `capture.mjs` and `pull-export.mjs` put them, the voice in
# `input/voice/`.
#
# Run it before any render. `render.mjs` does.
set -euo pipefail

# The video being staged is the folder this was run from (render.mjs passes
# it), and its media lands in `public/<subdir>/` — one subfolder per video, so
# a render of one cannot pick up a recording that belongs to the other.
project="${WB_PROJECT:-$PWD}"
sub="${1:-film}"
here="$(cd "$(dirname "$0")" && pwd)"
public="$here/../remotion/public"

# The app's own faces, and the demo clip the other three ads use.
"$here/../remotion/sync-assets.sh" >/dev/null

mkdir -p "$public/$sub"

# A clean slate each time, except `preview.mp4` — that is the render being
# sheeted by storyboard.mjs, not an input, and wiping it here would mean the
# storyboard could only ever be built in the same command as the render.
find "$public/$sub" -maxdepth 1 -type f ! -name 'preview*.mp4' -delete

shopt -s nullglob
copied=0
for f in "$project"/input/app/*.mp4; do
  case "$(basename "$f")" in
    *.raw.mp4) continue ;;   # the un-normalised screenrecord capture, VFR, not for the timeline
  esac
  cp "$f" "$public/$sub/"
  copied=$((copied + 1))
done

voice=0
for f in "$project"/input/voice/*; do
  cp "$f" "$public/$sub/"
  voice=$((voice + 1))
done

# The sound effects, which are generated by `make-sfx.mjs` rather than licensed
# from anywhere — see its header, and CREDITS.md.
sfx=0
for f in "$project"/input/sfx/*; do
  cp "$f" "$public/$sub/"
  sfx=$((sfx + 1))
done

echo "public/$sub is ready — $copied app clip(s), $voice voice file(s), $sfx sound(s)"

if [ "$copied" -eq 0 ]; then
  echo "  ! No app clips. Boot an emulator and run:  node ../pipeline/capture.mjs && node ../pipeline/pull-export.mjs" >&2
fi
