/**
 * Write `out/voiceover_script.md` from the config: what to record, in what
 * order, at what pace, into which filenames.
 *
 *   node ../pipeline/voiceover.mjs
 *
 * Generated so the script and the composition cannot disagree about a line.
 * If a beat's line changes, change it in `config.json`; hand-edits to the
 * markdown get overwritten.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { OUT, config } from './lib.mjs';

const cfg = config();
mkdirSync(OUT, { recursive: true });

const words = (s) => s.trim().split(/\s+/).filter(Boolean).length;
const row = (n, id, line, room) =>
  `| ${n} | ${id} | ${line} | ${words(line)} | ${room.toFixed(1)} s | ${(words(line) / room).toFixed(1)} w/s |`;

const bodyRows = cfg.beats.filter((b) => b.vo).map((b, i) => row(`body_${i + 1}`, b.id, b.vo, b.durationSec - 0.8));
const bodyWords = cfg.beats.reduce((n, b) => n + (b.vo ? words(b.vo) : 0), 0);
const bodySec = cfg.beats.reduce((n, b) => n + b.durationSec, 0);

const hookRows = (cfg.hooks ?? []).map((h, i) => row(`hook_${i + 1}`, h.id, h.vo, cfg.hookSec - 0.6));

const md = `# ${cfg.title} · voice script

Generated by \`../pipeline/voiceover.mjs\` from \`config.json\`. Do not edit by hand.

## The body — record these

${cfg.beats.filter((b) => b.vo).length} lines, ${bodyWords} words, about ${bodySec.toFixed(1)} seconds of picture.
One file per line, \`input/voice/body_1.mp3\` … \`body_${cfg.beats.length}.mp3\`, MP3 44.1 kHz,
silence trimmed at both ends. The timing script measures each file and lays
the picture out against what it measures, so half a second of leading room
becomes half a second of a shot nobody is talking over.

| file | beat | line | words | room | pace |
|---|---|---|---|---|---|
${bodyRows.join('\n')}

**One person, explaining something they built.** Not a narrator, not an
announcer, not the bright upward read that reads as an ad. Lowercase on the
page because it is lowercase in the mouth: short, flat, certain. The picture
is doing the arguing and the voice is agreeing with it.

The last line is flat on purpose. "one payment" is the claim; selling it with
the voice makes it sound like there is a catch.

## The hooks — optional

The hook's text is on screen inside its first second, because a large share of
viewers arrive muted, so a hook needs no voice to work. If the hooks are voiced,
record all six in one sitting so the energy matches across them — the six are
a controlled test of the hook and a read that is brighter on one of them is a
second variable. Files \`input/voice/hook_1.mp3\` … \`hook_${(cfg.hooks ?? []).length}.mp3\`.

| file | hook | line | words | room | pace |
|---|---|---|---|---|---|
${hookRows.join('\n')}

Three seconds is the hook's budget whatever is said over it: the body is
re-timed to the voice, the hook is not.

ElevenLabs starting point: **stability ~55, similarity ~75, style 0–10.**

## Label it

The voice is synthetic, so the AI-generated-content toggle goes **on** at upload.
`;

writeFileSync(resolve(OUT, 'voiceover_script.md'), md);
console.log(`out/voiceover_script.md — ${bodyRows.length} body lines, ${hookRows.length} hook lines`);
