/**
 * Regenerate `CREDITS.md`.
 *
 *   node scripts/credits.mjs
 *
 * This film has no outside footage in it at all, which is the interesting part
 * and the reason this file still exists: what it now records is *why* there is
 * nothing to credit, so the next video does not quietly reintroduce the problem.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { PROJECT, readJson } from '../../pipeline/lib.mjs';

const shots = readJson(resolve(PROJECT, 'app-shots.json'));
const rows = Object.values(shots.shots ?? {}).map(
  (s) => `| \`${s.file}\` | ${s.what} | ${s.width}×${s.height}, ${s.durationSec.toFixed(1)}s |`
);

const body = `# Credits — video 01, product film

Generated by \`scripts/credits.mjs\`. Do not edit by hand.

## There is no third-party footage in this film, on purpose

Every moving image in it is either the app's own export or a recording of the
app running. That is not thrift. \`STORE-ASSETS.md\` sets out the rule and the
reason:

> **Nobody collects a model release.** Pexels and Pixabay both allow commercial
> use and both state that they do not verify that the photographer had
> permission; the licences additionally forbid implying that a person depicted
> endorses your product. A face in a Play listing is an advertisement for the
> app, which is the exact use a release exists to cover.

**A paid social unit is more squarely an advertisement than a store listing is.**
An earlier cut of this project pulled five Pexels clips, every one of them
containing a recognisable person, and they were deleted rather than credited.
\`fetch-broll.mjs\` went with them: a stock-footage fetcher sitting in a paid-ad
project is an invitation to make the same mistake again in six months. If an
organic post ever wants stock, reintroduce it there, deliberately, and argue the
release question on its own terms.

## What the film is made of

| File | What | Size |
|---|---|---|
${rows.join('\n')}
| \`export.mp4\` | ${shots.export?.what ?? 'A real Wordburn export.'} | ${shots.export ? `${shots.export.width}×${shots.export.height}, ${shots.export.durationSec.toFixed(1)}s` : '—'} |

The recordings come off a booted emulator via \`scripts/capture.mjs\`; the export
comes off the same device via \`scripts/pull-export.mjs\` after exporting from
the app by hand. Neither is in git — they are rebuildable, and large.

The video *inside* the export is \`scripts/make-demo-clip.py\`'s output: plates
drawn in Pillow and a macOS \`say\` voice, both generated by this repository. It
has no face in it and no licence attached to it, which is the whole reason it
exists.

## Type

| Face | Where it came from | Licence |
|---|---|---|
| Be Vietnam Pro — ExtraBold, SemiBold, Medium | [Google Fonts](https://fonts.google.com/specimen/Be+Vietnam+Pro), bundled in \`assets/fonts/\` | [OFL 1.1](../../assets/fonts/BeVietnamPro-OFL.txt) |
| Spectral — ExtraBold | [Google Fonts](https://fonts.google.com/specimen/Spectral), bundled in \`assets/fonts/\` | [OFL 1.1](../../assets/fonts/Spectral-OFL.txt) |

The same five files the burn-in module sets its captions in. An ad for a
captions app that sets its type in a face the app does not own is advertising a
product nobody can download.

## Voice

Synthetic, made in ElevenLabs by Dennis, and his to use. Not in git — it is a
recording, not a build. TikTok's AI-generated-content label goes on at upload.

## Music

**Not chosen yet, and it is the only asset in this film that will come from
outside.** Whatever bed is used lands here first, with its source URL and a
licence that permits commercial use, before it is mixed. See the Music section
of \`out/voiceover_script.md\` for what to look for.

## Software

| Tool | Licence |
|---|---|
| [Remotion](https://remotion.dev) 4.0.290 | [Remotion License](https://remotion.dev/license) — free for individuals and companies under 4 employees, otherwise a paid company licence |
| ffmpeg / ffprobe | LGPL/GPL, used as a tool, nothing linked |
| Android SDK platform-tools (\`adb\`, \`screenrecord\`) | Android SDK Terms of Service |

**The Remotion licence is a real condition, not a formality.** Free for
individuals and for companies with fewer than four employees; past that it needs
a paid company licence. Wordburn is one person today, which is inside it.
`;

writeFileSync(resolve(PROJECT, 'CREDITS.md'), body);
console.log(`CREDITS.md — ${rows.length} app recording(s) + the export, no third-party footage`);
